[site]
title = "Borders"
out = "out"
resource_prefix = "https://borders.lod4hss.org/resource/"
label_predicate = "https://sdhss.org/ontology/shortcuts/P9"
shapes = [
  "/home/tav/repos/borders/shacl_files/shacl-Construction - Type ongoing.ttl",
  "/home/tav/repos/borders/shacl_files/profile-Construction - Location light ongoing-1.ttl",
  "/home/tav/repos/borders/shacl_files/shacl-Construction - Production and Destruction ongoing (1).ttl",
  "/home/tav/repos/borders/shacl_files/shacl-Geographical Place - Geocoordonates Light ongoing.ttl",
  "/home/tav/repos/borders/shacl_files/profile-Geographical Place - Type ongoing-1.ttl",
  "/home/tav/repos/borders/shacl_files/profile-Group - Type -1.ttl",
  "/home/tav/repos/borders/shacl_files/shacl-Group - Formation and Dissolution events.ttl",
  "traversals.ttl",
  "views.ttl",
]

[endpoint]
url = "https://sparql-gdb.lod4hss.org/borders"
